### ISSUE TITLE
Gmail sync problem

### ISSUE THREAD

**Issue by furrypotato** [loxK/android_device_htc_hero#14]
Gmaill sync seems very erratic.  Sometimes won't work at all, even by selecting 'Refresh' option inside gmail app.

**Comment by cbruegg** [comment]
This could be related to the Gmail.apk itself.. If so, we couldn't fix it..

**Comment by furrypotato** [comment]
I've wiped and reinstalled again and so far so good.
Main difference - I didn't select ' backup to google' option on startup' this time so it's a proper nice clean install. 
Will update later to see if it carries on working. But so far getting gmail notifications over gsm within a minute.

**Comment by loxK** [comment]
Google app are not part Office Cyanogen Mod.

**Comment by furrypotato** [comment]
Ah, ok.
