### ISSUE TITLE
Portable Wi-Fi Hotspots Support  missing

### ISSUE THREAD

**Issue by SynnaxCrab** [loxK/android_device_htc_hero#18]
Does the Hero hardware not support it ?
or  just missing in the test0 ROM?

**Comment by vorcigernix** [comment]
what is portable wifi? wireless tethering?

**Comment by cbruegg** [comment]
The driver doesn't support it - we need to incorporate the tether app then..

**Comment by loxK** [comment]
It is not supported by the hero hardware.

Did any of you tested the wifi tether app ? http://code.google.com/p/android-wifi-tether/

**Comment by Merdok59** [comment]
Works perfectly with all 2.1 roms (sense and vanilla).
Market version ("Wireless Tether for Root Users") tested on aHero, EzHero, VanillaEclair, VillainRom, Cromos, Official 2.1 rooted.

**Comment by SynnaxCrab** [comment]
I've seen the conversation between lox and cyanogen on Twitter. So it's the hardware problem.

And I've tested the "Wireless Tether for  Root Users", works great~

**Comment by loxK** [comment]
hey it is not a forum. Here we try to find fixes. What I mean is that "It is not supported by the hero hardware." is clear enough and we really don't care about other cooked roms.

So did any of you tested it on CM6 alpha for hero ??

**Comment by SynnaxCrab** [comment]
I'm sorry about my repeat. 

I've test the "Wireless Tether for Root Users" in the Market on CM6 alpha for hero. It works

I'm posting this via wireless tether

**Comment by loxK** [comment]
Sorry missed you comment.

Witch version did u use?

**Comment by loxK** [comment]
This version work http://code.google.com/p/android-wifi-tether/downloads/detail?name=wireless_tether_2_0_2.apk&can=2&q=

Closing as won't fix.
