### ISSUE TITLE
otapackage

### ISSUE THREAD

**Issue by vorcigernix** [loxK/android_device_htc_hero#2]
Me again :) I tried to fix otapackage by removing all mentions of recovery image..but I did something wrong probably. Can you describe changes needed to build update.zip?

**Comment by loxK** [comment]
I havn't tested otapackage. For now the goal is to have it run.

**Comment by vorcigernix** [comment]
so what's the procedure? this one: http://blog.coralic.nl/2010/01/25/how-to-create-update-zip-using-your-build-aka-system-img/ ?

**Comment by vorcigernix** [comment]
if so, can you post your update script here?

**Comment by loxK** [comment]
No. This is not the purpose of that Github repo. Here it is about building from sources. Wrong place!

There are plenty of rom to get inspired and write your own update-script. It is the easiest part in android cooking ...

**Comment by vorcigernix** [comment]
well, I know, I built source and I wanted to try it on my hero :) I always used otapackage, which had to be fixed sometimes, but always created correct update.zip
Now, if otapackage is out of play, what other options I have to load my new system image to hero?

**Comment by loxK** [comment]
Otapackage works for passion compilation I haven"t tried but there is no reason I see it would not for hero

Anyway it is much more easy to do:
fastboot flash system system.img

You will need the unlocked spl (shows s-off in fastboot mode)

**Comment by vorcigernix** [comment]
oh...I thought that this works only on real dev phones..thanks :)

**Comment by loxK** [comment]
I confirm that make otapackage works

**Comment by vorcigernix** [comment]
ok, ty
