### ISSUE TITLE
Won't boot

### ISSUE THREAD

**Issue by loxK** [loxK/android_device_htc_hero#3]
"Unable to dlopen(/system/lib/libandroid_servers.so): Cannot load library: link_image[1995]: failed to link libandroid_servers.so"

For some reason, libaudio is falling out of its prelinked space. A quick and dirty fix is to build it without prelinking (http://forum.xda-developers.com/showpost.php?p=6972487&postcount=56) but then it complains about libcamera.so:

http://paste2.org/p/896610

**Comment by koush** [comment]
Build with Camera stub. The camera stuff is proprietary, and you need Froyo compatible binaries. Maybe you can grab the camera binary meant for another phone and it may work...

**Comment by loxK** [comment]
Thanks Koush; with CAMERA_STUB it went further, but can you explain what this option means? Whereas I think it is not too bad, english is not my language so I sometime face  some difficulties to understand words in the android technical context....

Here is the logcat now, if any thought http://paste2.org/p/897772.

Are the Unknown permission android.permission warnings a problem ?

What may cause that "FATAL EXCEPTION IN SYSTEM PROCESS: PowerManagerService" ?

Regards

Thks

**Comment by loxK** [comment]
Hang on it boots. But I don't have the touch script working (display is ok)

What is handling it ?

Logcat: http://paste2.org/p/897778

**Comment by cbruegg** [comment]
Normally the kernel should handle the touchscreen.. And it seems like it does because Android recognizes the screen: 
New device: path=/dev/input/event1 name=synaptics-rmi-touchscreen id=0x10004 (of 0x5) index=5 fd=61 classes=0x14

**Comment by cbruegg** [comment]
Maybe the screen needs calibration? I'm not sure about that since capacitive touchscreens shouldn't need it but it should be worth a try.. if anyone knows how to.

**Comment by koush** [comment]
Camera stub uses a dummy interface (unimplemented, but functional in the sense it doesn't crash, but doesn't work). It prevents linkage to libcamera.so which is where you were failing.

**Comment by loxK** [comment]
Solved that was the kernel http://github.com/toastcfh/CdMa-HeRoC-2.6.29/blob/f7b1cfe912fc807f99fc2e856ed0f8e0bfca7d3c/drivers/input/touchscreen/synaptics_i2c_rmi.c-AOSP-fix

**Comment by cbruegg** [comment]
Ahhh I actually remember that one.. Just didn't remember it before =/ 
So everything except for the Camera is working now?

**Comment by loxK** [comment]
Yes

**Comment by sodnpoo** [comment]
I can verify that everything is working except for the camera
