### ISSUE TITLE
Jog-/Trackball LED doesn't work

### ISSUE THREAD

**Issue by cbruegg** [loxK/android_device_htc_hero#6]
Normally in CM, the jogball should light up on notifications (and I think the LED is just used for charging).
That fails with this vendor: notifications will let the LED turned on as long as the notification is still active.

**Comment by krispijn** [comment]
This seems the same problem as with the AOSP 2.1 roms; a (working) hack/fix was posted on XDA ( http://forum.xda-developers.com/showthread.php?t=705940 ) and looking at init.rc there seem to be similarities (missing chown commands etc.). That might be an angle worth investigating?

**Comment by cbruegg** [comment]
Here is the lights.c source with the jogball lights, courtesy of witysimon on XDA.

**Comment by loxK** [comment]
Thks a lot maxisma I will commit that

**Comment by loxK** [comment]
Seems it is not working for jogball ... Source have been included in device tree.

**Comment by vorcigernix** [comment]
in froydvillain jogball works...should be worth asking someone there
