### ISSUE TITLE
Camera partly fails - Shows laggy previews, but takes photos (3 MP max)

### ISSUE THREAD

**Issue by cbruegg** [loxK/android_device_htc_hero#7]
Video recording doesn't work either.

**Comment by loxK** [comment]
Please bro, provide a logcat when possible http://paste2.org/p/902837

**Comment by vorcigernix** [comment]
I have no previews and zoom sometimes crash whole app. Googles crash on start.
Will provide logcat l8r.

**Comment by cbruegg** [comment]
Preview works with Camera Magic from the Market..

**Comment by sodnpoo** [comment]
Maxisa - what changes did you make to get it to boot with the camera?

**Comment by cbruegg** [comment]
I just used the Alpha update.zip provided by loxK..

**Comment by sodnpoo** [comment]
:) cool - LoxK - what are the changes in the alpha update.zip?

**Comment by incomer** [comment]
a logcat of the camera app crash :) !

http://pastebin.com/mE8Pc89P

btw when you use Barcode scanner you can see through the camera, but not scan anything :(

**Comment by krispijn** [comment]
Same here, I've made a logcat while using the barcode scanner.. I get images, but there's no detection. http://paste2.org/p/903113 around line 660

**Comment by loxK** [comment]
The bug is confirmed. We have no need of x logcats showing the same error. Thks

**Comment by vorcigernix** [comment]
there is working ROM on G1 here: http://androidspin.com/2010/07/03/rom-kenmood-e-xtreme-froyo-v1-9-2-with-working-wifi-camera-3dgallery-for-t-mobile-g1-mt3g/
That guy fixed camera somehow (it is in changelog) but my google-fu failed and I can't find author :-/

**Comment by tewilove** [comment]
hi, how did you fix cannot locate '_ZN7android16CameraParameters3setEPKci'...?
i use c++filt and find that the symbol definitely exists and it is located on libcamera_client.so.

**Comment by vorcigernix** [comment]
I didn't :-/ 
there is working camera on G1, but their libraries does not work

**Comment by vorcigernix** [comment]
Did anyone found why cameramagic works? Do they call different api?

**Comment by vorcigernix** [comment]
This is now solved by cyanogen (don't ask me how :)
Is this repo still valid? I saw Lox is uploading something to http://github.com/CyanogenMod/android_device_htc_hero/tree/froyo-gsm-cdma
