### ISSUE TITLE
Froyo Apps2SD will only work after "pm setInstallLocation 2"

### ISSUE THREAD

**Issue by cbruegg** [loxK/android_device_htc_hero#8]
Nothing else to say here..

**Comment by hanness** [comment]
Just do it in adb ?

**Comment by mjedrasik** [comment]
I/PlatformUtils( 3330): Platform storage not supported for product: passion, manufacturer: HTC, device: hero. brand: htc, model: Hero, apiVersion: 8
could these be related?

**Comment by loxK** [comment]
Seems darchstar has a fix, it seems it is a kernel config issue (DM_CRYPT)

**Comment by loxK** [comment]
It is fixed upstream and will be in next alpha.
