### ISSUE TITLE
Color failures on lockscreen

### ISSUE THREAD

**Issue by cbruegg** [loxK/android_device_htc_hero#9]
This is related to our current kernel:
If the CPU is set to 245 MHz while waking up the device, the colors may go crazy, as well as the screen rotation.

**Comment by loxK** [comment]
Is that the default speed ?

**Comment by vorcigernix** [comment]
Default speed of this kernel, yes. Factory hero kernel have different.

**Comment by furrypotato** [comment]
This has been happening with 2.1 rom's too. 
Some Hero's don't wake very well from a low speed during sleep.
Tends to work ok if min clock speed is set to 352+

**Comment by loxK** [comment]
I use bundled kernel but no overclocking and I can t reproduce ...

**Comment by cbruegg** [comment]
But I had that error, too, so the bug is definetely confirmed.

**Comment by incomer** [comment]
i had it once too :), but get it too sleep and wake up again fixed it :)...

**Comment by vorcigernix** [comment]
Also run into this. It is no stopper, only thing I am afraid of is how phone responds to call in this half freeze status.
I am reporting thiss issue in cyanogen alpha, not this vendor provider.

**Comment by kosmiq** [comment]
Not a ROM-problem per se. The problem is that some phones are capable of waking up without issues from lower speeds, while others are not. For those with the problem, the only real fix is running setCPU or overclock-widget and set the screen-off speed higher. That will solve the problem.

Also note that the problem occurs less often for affected Heroes if the frequency table has less steps to jump through.

**Comment by vorcigernix** [comment]
I am afraid I can't agree with you. I think it will be good to have default kernel stepped as default (even if this means less battery life). 
What is a kernel used in cyanogen alpha?

**Comment by loxK** [comment]
I will provide a kernel with stock speed, working on it.

Please try this one: http://is.gd/dgxax

It is official kernel, I have just merge heroc with it, and no OC for now.

**Comment by vorcigernix** [comment]
Built and posted on http://bit.ly/9Y1n5f
Dunno how to make update.zip from this :-/

**Comment by loxK** [comment]
Sorry, I sent the wrong URL !

Here you go: http://dl.dropbox.com/u/6729720/Android/Misc/update-cm-6.0.0-Hero-All-kernel-signed.zip

**Comment by vorcigernix** [comment]
uploaded to link above and testing now

**Comment by vorcigernix** [comment]
Oh there are some big problems in this update, don't try it.
 //
I was out of sync with my sources, did u used my files LoxK?

**Comment by tewilove** [comment]
i tried official kernel and the problem still exists
i found that the request to camera to get a frame is rejected by kernel for wrong parameters, i tried to omit these and previewing seems work but breaks recording. i think we need some work on libcamera

**Comment by vorcigernix** [comment]
ok, how did u tested it? Did you followed this ?: http://wiki.cyanogenmod.com/index.php/How_to_build_a_kernel_port
or is there some more simple way?

**Comment by tewilove** [comment]
I intended to post this to camera issue, but it seems something went wrong:(

**Comment by vorcigernix** [comment]
I built an official kernel and inserted in update, it boots ok, but uouchscreen does not work. Lox had this issue, maybe he know how to fix it.

**Comment by tewilove** [comment]
Well, you can use ts driver from godmode, the file name is ***AOSP-fix, just simplely overwrite the original one.

**Comment by vorcigernix** [comment]
Ok, I compiled official kernel with fixes from godmode. Update is on http://bit.ly/9Y1n5f
I tried to fix camera problem, but it is working even worse now (sometimes freeze whole phone). I didn't run into this topic issue though.
Offikernel.zip is just kernel update, second file is whole build with default kernel.

**Comment by tewilove** [comment]
i've made some change to msm_camera.c and now previewing is working, but recording freezes the camera...

**Comment by vorcigernix** [comment]
in htc kernel or godmode?

**Comment by tewilove** [comment]
in htc kernel, the driver seems only copy captured data to user space, no hardware controlling code(done in liboemcamera.so, and this is the main reason why camera is broken), i just remove some checks.
